version: '3.8'

services:
  food-api:
    build: .
    container_name: food-recognition-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      # Mount logs directory for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: food-api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - food-api
    restart: unless-stopped

volumes:
  logs: