global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'food-ml-service'
    static_configs:
      - targets: ['food-ml-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'food_classifier_.*'
        action: keep

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']