server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: food-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: food-api
          service: food-recognition
          __path__: /app/logs/*.log

  - job_name: food-api-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: food-api-access
          service: food-recognition
          __path__: /app/logs/access.log